name: "RabbitMQ"
description: "Rabbit message queue"
version: "3.10.5"
slug: "rabbitmq"
init: true
ingress: true
ingress_port: 15672
ports:
  15672/tcp: 15672
ports_description:
  15672/tcp: Web interface
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386